script: bin/bacon -Ilib --automatic --quiet
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.10
- 2.2.7
- 2.3.4
- 2.4.1
- ruby-head
- rbx-18mode
- rbx-19mode
- jruby-18mode
- jruby-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  recipients:
  - gabriel.horner@gmail.com
