script: bin/bacon -Ilib --automatic --quiet
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.10
- 2.2.9
- 2.3.7
- 2.4.4
- 2.5.1
- rbx-18mode
- rbx-19mode
- jruby-18mode
- jruby-19mode
notifications:
  recipients:
  - gabriel.horner@gmail.com
